<a href="https://colab.research.google.com/github/PosgradoMNA/actividades-de-aprendizaje-murasakiw/blob/main/Semana_3_Python_for_Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Nombre: Sergio Omar Esparza Hernández

Matrícula: A01794338

#Python for Data Science (IBM): Módulo 5

##Numpy 1D Arrays

Numpy es una librería utilizada para realizar cálculos computacionales científicos

Pandas está basada en Numpy

Un arreglo de Numpy es similar a una lista, usualmente está fijo su tamaño y 
cada elemento es del mismo tipo.

Para utilizar Numpy, primero es necesario importar esta librería.

In [ ]:
import numpy as np #Es necesario importar la librería para poder utilizar las operaciones

In [ ]:
a = np.array([0, 1, 2, 3, 4]) #Se puede utilizar una lista de python para crear un array de numpy
a

array([0, 1, 2, 3, 4])

In [ ]:
a[3] #Se puede acceder a los valores individuales del array de igual manera que con las listas, a través de índices

3

In [ ]:
type(a) #El tipo de dato de los arrays de numpy es numpy.ndarray

numpy.ndarray

In [ ]:
a.dtype #Con el atributo dtype se puede obtener el tipo de todos los datos almacenados en el array

dtype('int64')

Atributos de los arrays de numpy

In [ ]:
a.size #Devuelve el número de elementos que contiene el array

5

In [ ]:
a.ndim #Devuelve el número de dimensiones del array

1

In [ ]:
a.shape #Devuelve una tupla con el tamaño del arreglo en cada dimensión

(5,)

Métodos para indexing y slicing

In [ ]:
c = np.array([20, 1, 2, 3, 4])
c[0] = 100 #Se puede modificar el valor que hay en una posición del array, de igual manera que con las listas
c

array([100,   1,   2,   3,   4])

In [ ]:
#Se puede obtener un slice de un numpy array al igual que con las listas y tuplas de Python
d = c[1:4] 
d

array([1, 2, 3])

In [ ]:
c[3:5] = 300, 400 #Asignar a los índices correspondientes nuevos valores
c

array([100,   1,   2, 300, 400])

Operaciones básicas

Estas operaciones son usualmente más rápidas computacionalmente y requieren menos memoria en numpy comparado con un código regular de Python

In [ ]:
#Suma de vectores con numpy
#Es más sencillo y más rápido realizar una suma de vectores utilizando numpy
#Esto es importante cuando se tienen arrays con muchos datos
u = np.array([1, 0])
v = np.array([0, 1])
z = u + v
z

array([1, 1])

In [ ]:
#Resta de vectores con numpy
u = np.array([1, 0])
v = np.array([0, 1])
z = u - v
z

array([ 1, -1])

In [ ]:
#Multiplicación de un vector por un escalar
#Esta operación solo requiere una línea de código con numpy
y = np.array([1, 2])
z = 2 * y
z

array([2, 4])

In [ ]:
#Producto de Hadamard
#Consiste en multiplicar los elementos que se encuentran en la misma posición en los dos vectores
u = np.array([1, 2])
v = np.array([3, 2])
z = u * v
z

array([3, 4])

In [ ]:
#Producto punto utilizando numpy
#Este producto es útil para verificar si dos vectores son perpendiculares
#El resultado es una magnitud escalar
u = np.array([1, 2])
v = np.array([3, 2])
z =  np.dot(u, v)
z

7